[project]
name = "qjph"
description = "Quick Json Parser Hack"
version = "0.0.1"
requires-python = ">= 3.10"

authors = [
  {name = "kagekirin", email = "kagekirin@gmail.com"},
]
maintainers = [
  {name = "kagekirin", email = "kagekirin@gmail.com"},
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]